<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1141" started-at="2017-03-03T03:58:04Z" finished-at="2017-03-03T03:58:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1141" started-at="2017-03-03T03:58:04Z" finished-at="2017-03-03T03:58:06Z">
      <class name="models.AccountTests">
        <test-method status="FAIL" signature="accountCreateRecord()[pri:0, instance:models.AccountTests@3b084709]" name="accountCreateRecord" duration-ms="976" started-at="2017-03-02T22:58:04Z" finished-at="2017-03-02T22:58:05Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at models.AccountTests.accountCreateRecord(AccountTests.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- accountCreateRecord -->
        <test-method status="PASS" signature="accountUpdateRecord()[pri:0, instance:models.AccountTests@3b084709]" name="accountUpdateRecord" duration-ms="152" started-at="2017-03-02T22:58:05Z" finished-at="2017-03-02T22:58:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- accountUpdateRecord -->
      </class> <!-- models.AccountTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
